title: "ATHUL JOSE"
email: ""
description: >-
  Student in International Business | Designer | Photographer | Writer

# Social
twitter_username: athuljose0609
github_username: athuljose0609

# Theme settings
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Berlin

# Include folders
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Author Profile
author:
  name   : "Athul Jose"
  avatar : "/assets/images/bio-photo.jpg"   # make sure the image exists
  bio    : "Master's student | Designer | Photographer | Blogger"
  location: "Germany"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/athul-jose-17b88a319/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/athuljose0609"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/athuljsep"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:athuljose0609@gmail.com"

# Footer Social Links
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/athuljose0609"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/athuljsep"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/athul-jose-17b88a319/"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
